// Generated by scripts/generate_rpc_types.py. Do not edit by hand.
export type ManagedGroupListOut = {
  id: number
  created_at: string
  updated_at: string
  group_id: number
  name: string
  priority: number
  enabled: boolean
  max_members: number
  current_members: number
  join_url: string
  min_qq_level: number
  max_wrong_answers: number
  wrong_answer_window_hours: number
  redirect_message_template: string
  note: string
}
export type AnswerRuleListOut = {
  id: number
  created_at: string
  updated_at: string
  name: string
  enabled: boolean
  group_id: number | null
  match_mode: 'contains' | 'exact' | 'regex'
  logic_mode: 'any' | 'all'
  patterns: string[]
}
export type MessageModerationRuleListOut = {
  id: number
  created_at: string
  updated_at: string
  name: string
  enabled: boolean
  group_id: number | null
  patterns: string[]
  cloud_review_enabled: boolean
  ocr_enabled: boolean
  image_review_enabled: boolean
  action: 'recall' | 'mute' | 'recall_and_mute'
  mute_duration_seconds: number
  note: string
}
export type JoinBlacklistListOut = {
  id: number
  created_at: string
  updated_at: string
  user_id: number
  enabled: boolean
  reason: string
  note: string
}
export type DedupeWhitelistListOut = {
  id: number
  created_at: string
  updated_at: string
  user_id: number
  enabled: boolean
  note: string
}
export type AnnouncementListOut = {
  id: number
  group_id: number
  notice_id: string
  sender_id: number | null
  title: string
  content: string
  created_at: string
  synced_at: string
}
export type EssenceMessageListOut = {
  id: number
  group_id: number
  message_id: number
  sender_id: number | null
  operator_id: number | null
  content: string
  created_at: string
  synced_at: string
}
export type GroupFileListOut = {
  id: number
  group_id: number
  file_id: string
  folder_id: string
  file_name: string
  busid: number | null
  size: number | null
  upload_time: string | null
  uploader_id: number | null
  synced_at: string
}
export type JoinRequestListOut = {
  id: number
  flag: string
  user_id: number
  group_id: number
  answer_text: string
  qq_level: number | null
  wrong_answer_count: number
  apply_status: string
  apply_error: string
  matched_rule_id: number | null
  recommended_group_id: number | null
  result: string
  reason: string
  created_at: string
}
export type LeaveEventListOut = {
  id: number
  group_id: number
  user_id: number
  operator_id: number | null
  sub_type: string
  created_at: string
}
export type AuditLogListOut = {
  id: number
  admin_id: number | null
  action: string
  target: string
  created_at: string
}
export type DedupeActionListOut = {
  id: number
  job_id: number
  user_id: number
  keep_group_id: number
  kick_group_id: number
  nickname: string
  status: string
  error: string
  created_at: string
  executed_at: string | null
}
export type AdminJobListOut = {
  id: number
  created_at: string
  updated_at: string
  admin_id: number
  request_id: string
  kind: string
  status: string
  summary: Record<string, unknown>
  dedupe_job_id: number | null
}
export type AdminJobItemListOut = {
  id: number
  job_id: number
  group_id: number
  status: string
  error: string
}
export type ManagedGroupDetailOut = {
  id: number
  created_at: string
  updated_at: string
  group_id: number
  name: string
  priority: number
  enabled: boolean
  max_members: number
  current_members: number
  join_url: string
  min_qq_level: number
  max_wrong_answers: number
  wrong_answer_window_hours: number
  redirect_message_template: string
  note: string
}
export type AnswerRuleDetailOut = {
  id: number
  created_at: string
  updated_at: string
  name: string
  enabled: boolean
  group_id: number | null
  match_mode: 'contains' | 'exact' | 'regex'
  logic_mode: 'any' | 'all'
  patterns: string[]
}
export type MessageModerationRuleDetailOut = {
  id: number
  created_at: string
  updated_at: string
  name: string
  enabled: boolean
  group_id: number | null
  patterns: string[]
  cloud_review_enabled: boolean
  ocr_enabled: boolean
  image_review_enabled: boolean
  action: 'recall' | 'mute' | 'recall_and_mute'
  mute_duration_seconds: number
  note: string
}
export type JoinBlacklistDetailOut = {
  id: number
  created_at: string
  updated_at: string
  user_id: number
  enabled: boolean
  reason: string
  note: string
}
export type DedupeWhitelistDetailOut = {
  id: number
  created_at: string
  updated_at: string
  user_id: number
  enabled: boolean
  note: string
}
export type AnnouncementDetailOut = {
  id: number
  group_id: number
  notice_id: string
  sender_id: number | null
  title: string
  content: string
  created_at: string
  synced_at: string
  raw_data: Record<string, unknown>
}
export type EssenceMessageDetailOut = {
  id: number
  group_id: number
  message_id: number
  sender_id: number | null
  operator_id: number | null
  content: string
  created_at: string
  synced_at: string
  raw_data: Record<string, unknown>
}
export type GroupFileDetailOut = {
  id: number
  group_id: number
  file_id: string
  folder_id: string
  file_name: string
  busid: number | null
  size: number | null
  upload_time: string | null
  uploader_id: number | null
  synced_at: string
  raw_data: Record<string, unknown>
}
export type JoinRequestDetailOut = {
  id: number
  flag: string
  user_id: number
  group_id: number
  answer_text: string
  qq_level: number | null
  wrong_answer_count: number
  apply_status: string
  apply_error: string
  matched_rule_id: number | null
  recommended_group_id: number | null
  result: string
  reason: string
  created_at: string
  raw_event: Record<string, unknown>
}
export type LeaveEventDetailOut = {
  id: number
  group_id: number
  user_id: number
  operator_id: number | null
  sub_type: string
  created_at: string
  raw_event: Record<string, unknown>
}
export type AuditLogDetailOut = {
  id: number
  admin_id: number | null
  action: string
  target: string
  created_at: string
  detail: Record<string, unknown>
}
export type DedupeActionDetailOut = {
  id: number
  job_id: number
  user_id: number
  keep_group_id: number
  kick_group_id: number
  nickname: string
  status: string
  error: string
  created_at: string
  executed_at: string | null
}
export type AdminJobDetailOut = {
  id: number
  created_at: string
  updated_at: string
  admin_id: number
  request_id: string
  kind: string
  status: string
  summary: Record<string, unknown>
  dedupe_job_id: number | null
  params: Record<string, unknown>
}
export type AdminJobItemDetailOut = {
  id: number
  job_id: number
  group_id: number
  status: string
  error: string
  detail: Record<string, unknown>
}
export type ManagedGroupIn = {
  group_id: number
  name?: string
  priority?: number
  enabled?: boolean
  max_members?: number
  current_members?: number
  join_url?: string
  min_qq_level?: number
  max_wrong_answers?: number
  wrong_answer_window_hours?: number
  redirect_message_template?: string
  note?: string
}
export type ManagedGroupPatch = {
  name?: string | null
  priority?: number | null
  enabled?: boolean | null
  max_members?: number | null
  current_members?: number | null
  join_url?: string | null
  min_qq_level?: number | null
  max_wrong_answers?: number | null
  wrong_answer_window_hours?: number | null
  redirect_message_template?: string | null
  note?: string | null
}
export type AnswerRuleIn = {
  name: string
  enabled?: boolean
  group_id?: number | null
  match_mode?: 'contains' | 'exact' | 'regex'
  logic_mode?: 'any' | 'all'
  patterns?: string[]
}
export type AnswerRulePatch = {
  name?: string | null
  enabled?: boolean | null
  group_id?: number | null
  match_mode?: 'contains' | 'exact' | 'regex' | null
  logic_mode?: 'any' | 'all' | null
  patterns?: string[] | null
}
export type JoinBlacklistIn = { user_id: number; enabled?: boolean; reason?: string; note?: string }
export type JoinBlacklistPatch = {
  enabled?: boolean | null
  reason?: string | null
  note?: string | null
}
export type MessageModerationRuleIn = {
  name: string
  enabled?: boolean
  group_id?: number | null
  patterns?: string[]
  cloud_review_enabled?: boolean
  ocr_enabled?: boolean
  image_review_enabled?: boolean
  action?: 'recall' | 'mute' | 'recall_and_mute'
  mute_duration_seconds?: number
  note?: string
}
export type MessageModerationRulePatch = {
  name?: string | null
  enabled?: boolean | null
  group_id?: number | null
  patterns?: string[] | null
  cloud_review_enabled?: boolean | null
  ocr_enabled?: boolean | null
  image_review_enabled?: boolean | null
  action?: 'recall' | 'mute' | 'recall_and_mute' | null
  mute_duration_seconds?: number | null
  note?: string | null
}
export type DedupeWhitelistIn = { user_id: number; note?: string; enabled?: boolean }
export type DedupeWhitelistPatch = { note?: string | null; enabled?: boolean | null }
export type ImageReviewChannelIn = {
  id: string
  name?: string
  enabled?: boolean
  base_url?: string
  model?: string
  response_format?: 'tool_call' | 'json_schema' | 'json_object' | 'none'
  reasoning_effort?: '' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  max_completion_tokens?: number
  extra_body?: Record<string, unknown>
  image_detail?: 'auto' | 'low' | 'high' | 'original'
  timeout_seconds?: number
  api_key?: string
  clear_api_key?: boolean
}
export type ImageReviewChannelOut = {
  id: string
  name?: string
  enabled?: boolean
  base_url?: string
  model?: string
  response_format?: 'tool_call' | 'json_schema' | 'json_object' | 'none'
  reasoning_effort?: '' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  max_completion_tokens?: number
  extra_body?: Record<string, unknown>
  image_detail?: 'auto' | 'low' | 'high' | 'original'
  timeout_seconds?: number
  api_key_configured: boolean
}
export type ImageReviewConfigIn = {
  enabled?: boolean
  system_prompt?: string
  min_confidence?: number
  channels?: {
    id: string
    name?: string
    enabled?: boolean
    base_url?: string
    model?: string
    response_format?: 'tool_call' | 'json_schema' | 'json_object' | 'none'
    reasoning_effort?: '' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    max_completion_tokens?: number
    extra_body?: Record<string, unknown>
    image_detail?: 'auto' | 'low' | 'high' | 'original'
    timeout_seconds?: number
    api_key?: string
    clear_api_key?: boolean
  }[]
}
export type ImageReviewConfigOut = {
  enabled: boolean
  system_prompt: string
  default_system_prompt?: string
  min_confidence: number
  channels: {
    id: string
    name?: string
    enabled?: boolean
    base_url?: string
    model?: string
    response_format?: 'tool_call' | 'json_schema' | 'json_object' | 'none'
    reasoning_effort?: '' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max'
    max_completion_tokens?: number
    extra_body?: Record<string, unknown>
    image_detail?: 'auto' | 'low' | 'high' | 'original'
    timeout_seconds?: number
    api_key_configured: boolean
  }[]
}
export type ResourceRows = {
  groups: ManagedGroupListOut & { [key: string]: unknown }
  rules: AnswerRuleListOut & { [key: string]: unknown }
  moderation: MessageModerationRuleListOut & { [key: string]: unknown }
  blacklist: JoinBlacklistListOut & { [key: string]: unknown }
  whitelist: DedupeWhitelistListOut & { [key: string]: unknown }
  notices: AnnouncementListOut & { [key: string]: unknown }
  essence: EssenceMessageListOut & { [key: string]: unknown }
  files: GroupFileListOut & { [key: string]: unknown }
  joins: JoinRequestListOut & { [key: string]: unknown }
  leaves: LeaveEventListOut & { [key: string]: unknown }
  audits: AuditLogListOut & { [key: string]: unknown }
  actions: DedupeActionListOut & { [key: string]: unknown }
  jobs: AdminJobListOut & { [key: string]: unknown }
  'job-items': AdminJobItemListOut & { [key: string]: unknown }
}
export type ResourceDetails = {
  groups: ManagedGroupDetailOut & { [key: string]: unknown }
  rules: AnswerRuleDetailOut & { [key: string]: unknown }
  moderation: MessageModerationRuleDetailOut & { [key: string]: unknown }
  blacklist: JoinBlacklistDetailOut & { [key: string]: unknown }
  whitelist: DedupeWhitelistDetailOut & { [key: string]: unknown }
  notices: AnnouncementDetailOut & { [key: string]: unknown }
  essence: EssenceMessageDetailOut & { [key: string]: unknown }
  files: GroupFileDetailOut & { [key: string]: unknown }
  joins: JoinRequestDetailOut & { [key: string]: unknown }
  leaves: LeaveEventDetailOut & { [key: string]: unknown }
  audits: AuditLogDetailOut & { [key: string]: unknown }
  actions: DedupeActionDetailOut & { [key: string]: unknown }
  jobs: AdminJobDetailOut & { [key: string]: unknown }
  'job-items': AdminJobItemDetailOut & { [key: string]: unknown }
}
export type ResourceInputs = {
  groups: { create: ManagedGroupIn; update: ManagedGroupPatch }
  rules: { create: AnswerRuleIn; update: AnswerRulePatch }
  blacklist: { create: JoinBlacklistIn; update: JoinBlacklistPatch }
  moderation: { create: MessageModerationRuleIn; update: MessageModerationRulePatch }
  whitelist: { create: DedupeWhitelistIn; update: DedupeWhitelistPatch }
}
