"""Generate resource contracts from Pydantic DTOs. Run from the repository root."""

import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))

from app.schemas.resources import DETAIL_MODELS, LIST_MODELS  # noqa: E402
from app.schemas import admin  # noqa: E402


def ts_type(schema: dict, definitions: dict) -> str:
    if "$ref" in schema:
        return ts_type(definitions[schema["$ref"].split("/")[-1]], definitions)
    if "anyOf" in schema:
        return " | ".join(ts_type(option, definitions) for option in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"({ts_type(schema['items'], definitions)})[]"
    if kind == "object":
        if "properties" not in schema:
            extra = schema.get("additionalProperties", {})
            return f"Record<string, {ts_type(extra, definitions) if isinstance(extra, dict) else 'unknown'}>"
        required = schema.get("required", [])
        fields = [
            f"{key}{'' if key in required else '?'}: {ts_type(value, definitions)}"
            for key, value in schema["properties"].items()
        ]
        return "{ " + "; ".join(fields) + " }"
    return {
        "integer": "number",
        "number": "number",
        "string": "string",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def declaration(name, model):
    schema = model.model_json_schema()
    return f"export type {name} = {ts_type(schema, schema.get('$defs', {}))}\n"


def render():
    result = "// Generated by scripts/generate_rpc_types.py. Do not edit by hand.\n"
    for models in (LIST_MODELS, DETAIL_MODELS):
        for model in models.values():
            result += declaration(model.__name__, model)
    schemas = {
        "groups": (admin.ManagedGroupIn, admin.ManagedGroupPatch),
        "rules": (admin.AnswerRuleIn, admin.AnswerRulePatch),
        "blacklist": (admin.JoinBlacklistIn, admin.JoinBlacklistPatch),
        "moderation": (admin.MessageModerationRuleIn, admin.MessageModerationRulePatch),
        "whitelist": (admin.DedupeWhitelistIn, admin.DedupeWhitelistPatch),
    }
    for create, patch in schemas.values():
        result += declaration(create.__name__, create) + declaration(patch.__name__, patch)
    for name, models in (("ResourceRows", LIST_MODELS), ("ResourceDetails", DETAIL_MODELS)):
        result += f"export type {name} = {{\n"
        result += "".join(
            f"  '{resource}': {model.__name__} & {{ [key: string]: unknown }}\n"
            for resource, model in models.items()
        )
        result += "}\n"
    result += "export type ResourceInputs = {\n"
    result += "".join(
        f"  '{resource}': {{ create: {create.__name__}; update: {patch.__name__} }}\n"
        for resource, (create, patch) in schemas.items()
    )
    return result + "}\n"


if __name__ == "__main__":
    target = root / "frontend/src/api/generated.ts"
    target.write_text(render(), encoding="utf-8")
